# Generated by Django 2.2.24 on 2022-07-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='is_std',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_std',
            field=models.BooleanField(default=True),
        ),
    ]
